# Generated by Django 4.2.2 on 2023-08-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Interest Rate'),
        ),
    ]
