# Generated by Django 4.2.2 on 2023-08-20 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_alter_loan_interest_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='installment',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=15, verbose_name='Installment'),
            preserve_default=False,
        ),
    ]
