# Generated by Django 4.2.2 on 2023-08-20 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_loan_installment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='arrears',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Arrears'),
        ),
    ]
