# Generated by Django 4.2.2 on 2023-08-23 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_loan_payed_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='payed_amount',
            new_name='payable_amount',
        ),
    ]
