# Generated by Django 4.2.2 on 2023-08-23 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_rename_payed_amount_loan_payable_amount'),
    ]

    operations = [
        migrations.RenameModel('Group', 'LoanGroup')
    ]
