# Generated by Django 4.2.2 on 2023-08-23 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0008_auto_20230823_1609'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loangroup',
            options={'ordering': ['id'], 'verbose_name': 'Loan Group', 'verbose_name_plural': 'Loan Groups'},
        ),
    ]
