# Generated by Django 4.2.2 on 2023-10-09 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0009_alter_loangroup_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loangroup',
            name='investors',
        ),
    ]
