# Generated by Django 4.2.2 on 2023-10-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0011_investor_loangroup_investors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loangroup',
            name='investors',
            field=models.ManyToManyField(blank=True, related_name='loan_groups', to='loans.investor', verbose_name='Investors'),
        ),
    ]
