# Generated by Django 4.2.2 on 2023-08-01 10:45

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='Id')),
                ('first_name', models.CharField(max_length=127, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=127, verbose_name='Last Name')),
                ('nic', models.CharField(max_length=15, verbose_name='NIC')),
                ('address', models.CharField(max_length=1023, verbose_name='Address')),
                ('shop_name', models.CharField(max_length=127, verbose_name='Shop Name')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('route', models.CharField(blank=True, max_length=63, null=True, verbose_name='Route')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['id'],
            },
        ),
    ]
